before:
  hooks:
    - go mod download
builds:
  - main: ./main.go
    binary: cryptex
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.GitCommit={{.ShortCommit}}
    goos:
      - linux
      - windows
      - darwin
archives:
  - format: tar.gz
    # if the OS is windows, we override and put everything in a .zip instead.
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .ShortCommit }}-next"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: mas2020-golang
      name: homebrew-cryptex
    folder: Formula
    homepage: https://github.com/mas2020-golang/cryptex
    description: |
    Secure your secrets with a powerful and easy to use CLI application
